# ── Stage 1: Install dependencies ─────────────────────────────────────────────
FROM node:22-alpine AS deps

WORKDIR /app

# Only copy package files — layer cache means npm ci only reruns when these change
COPY package.json package-lock.json* ./
RUN npm ci --frozen-lockfile


# ── Stage 2: Build ────────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

WORKDIR /app

# Copy deps from stage 1
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files
COPY . .

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build


# ── Stage 3: Production runtime ───────────────────────────────────────────────
# Uses standalone output — node_modules and dev deps are NOT copied here.
# Final image only contains what Next.js needs to serve the app.
FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3030
ENV HOSTNAME="0.0.0.0"

# Create non-root user before copying files
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Standalone output produces a self-contained server.js with its own
# minimal node_modules — no need to copy the full 200MB+ node_modules
COPY --from=builder --chown=appuser:appgroup /app/.next/standalone ./
COPY --from=builder --chown=appuser:appgroup /app/.next/static ./.next/static
COPY --from=builder --chown=appuser:appgroup /app/public ./public

USER appuser

EXPOSE 3030

# server.js is generated by Next.js standalone — no next binary needed
CMD ["node", "server.js"]